javascripts:
  common:
    - public/vendor/jquery-1.5.2.js
    - public/vendor/underscore.js    
    - public/vendor/backbone.js
    - public/vendor/rails.js
  profile:
    - public/vendor/jscolor/jscolor.js
    - public/javascripts/application.js
    # - public/javascripts/models/swatch.js
    # - public/javascripts/views/paintbox.js
    # - public/javascripts/views/swatch.js

stylesheets:
  common:
    - public/stylesheets/application.css